### ISSUE TITLE
BUTTON_* constants are unnecessary

### ISSUE THREAD

**Issue by ketsuban** [eevee/anise-cheezball-rising#3]
Currently you define eight `BUTTON_*` constants, but `hardware.inc` already has these (`PADB_*` for bitwise instructions, `PADF_*` for masks). To switch to using them you'd need to change the `swap a` in `read_input` ([here](https://github.com/eevee/anise-cheezball-rising/blob/master/src/main.rgbasm#L426)) to `swap b`, since you have the nybbles in the opposite order to its expectations.

**Comment by eevee** [comment]
Oh, so it does.  Odd, since those aren't strictly related to the hardware.  I'll switch over to them; I was going to change the `swap` anyway.

**Comment by ketsuban** [comment]
This issue was resolved by commit b6be6b62.
